"""
Albion spell / passive catalog (read-only).

Loads the static spell seed generated by scripts/generate_spell_seed.py
(app/albion/data/spells.json) and exposes per-item spell lookups. Unlike
IronkeepV1's albion_spells.py, this module performs NO network access and runs
NO background threads — production reads only the committed seed file.

Spell data is keyed by item base-type (e.g. MAIN_MACE, ARMOR_PLATE_AVALON),
derived from an item_id by stripping the tier prefix and enchantment suffix.

Storage / field-key model
-------------------------
A build stores at most one spell name per "field key". A field key is
``<slot_prefix>_<field_suffix>`` where slot_prefix maps an equipment slot to
the V1 naming and field_suffix comes from the spell slot (spell_q / spell_w /
spell_e / passive / passive_2 / spell). Example: main_hand Q -> weapon_spell_q.
"""

from __future__ import annotations

import json
import re
import urllib.parse
from pathlib import Path

_SPELL_RENDER = "https://render.albiononline.com/v1/spell"
_DEFAULT_SEED_PATH: Path = Path(__file__).parent / "data" / "spells.json"


def _spell_render_url(key: str, size: int) -> str:
    """Build a spell icon URL, routing through the icon proxy when enabled."""
    if not key:
        return ""
    from app.albion import icon_proxy
    if icon_proxy.is_enabled():
        return icon_proxy.spell_proxy_url(key, size)
    return f"{_SPELL_RENDER}/{urllib.parse.quote(key)}.png?size={size}"

#: Equipment slot -> V1-style field-key prefix. Only these slots carry spells.
SPELL_SLOT_PREFIX: dict[str, str] = {
    "main_hand": "weapon",
    "off_hand":  "offhand",
    "head":      "head",
    "chest":     "chest",
    "shoes":     "shoes",
    "cape":      "cape",
}

#: Every field key a build may store a spell under.
VALID_SPELL_FIELD_KEYS: frozenset[str] = frozenset({
    "weapon_spell_q", "weapon_spell_w", "weapon_spell_e", "weapon_passive",
    "head_spell", "head_passive",
    "chest_spell", "chest_passive", "chest_passive_2",
    "shoes_spell", "shoes_passive",
    "offhand_passive",
    "cape_passive",
})


def get_base_type(item_id: str) -> str:
    """T7_MAIN_MACE@2 -> MAIN_MACE."""
    base = (item_id or "").split("@")[0]
    m = re.match(r"^T\d+_(.*)", base)
    return m.group(1) if m else base


class AlbionSpellCatalog:
    """Read-only in-memory spell catalog keyed by item base-type."""

    def __init__(self, spells: dict[str, dict]) -> None:
        self._spells: dict[str, dict] = spells
        # Reverse index: spell display name -> icon_id (for server-rendered icons)
        by_name: dict[str, str] = {}
        by_lower: dict[str, str] = {}
        for entry in spells.values():
            for slot in entry.get("slots", []):
                for sp in slot.get("spells", []):
                    name = (sp.get("name") or "").strip()
                    icon_id = (sp.get("icon_id") or "").strip()
                    if not name or not icon_id:
                        continue
                    by_name.setdefault(name, icon_id)
                    by_lower.setdefault(name.lower(), icon_id)
        self._icon_by_name = by_name
        self._icon_by_name_lower = by_lower

    # ------------------------------------------------------------------

    def get_for_item(self, item_id: str) -> dict | None:
        """Return {item_type, slots:[...]} for an item_id, or None on miss."""
        if not item_id:
            return None
        entry = self._spells.get(get_base_type(item_id))
        if not entry:
            return None
        return {
            "item_type": entry.get("item_category"),
            "slots": [
                {
                    "label": s.get("label") or "",
                    "field_suffix": s.get("field_suffix") or "",
                    "spells": [
                        {
                            "name": sp.get("name") or "",
                            "icon_id": sp.get("icon_id") or "",
                            # Recompute so the proxy setting is honoured (the
                            # seed stores absolute CDN URLs).
                            "icon_url": _spell_render_url(
                                sp.get("icon_id") or sp.get("name") or "", 40
                            ),
                            "description": sp.get("description") or "",
                        }
                        for sp in (s.get("spells") or [])
                    ],
                }
                for s in (entry.get("slots") or [])
            ],
        }

    def field_options_for_item(self, slot: str, item_id: str) -> dict[str, set[str]]:
        """Return {field_key: {allowed spell names}} for an item in a slot.

        Used by persistence to validate that a submitted spell belongs to the
        item actually equipped in that slot.
        """
        prefix = SPELL_SLOT_PREFIX.get(slot)
        if not prefix:
            return {}
        data = self.get_for_item(item_id)
        if not data:
            return {}
        out: dict[str, set[str]] = {}
        for s in data["slots"]:
            field_key = f"{prefix}_{s['field_suffix']}"
            if field_key not in VALID_SPELL_FIELD_KEYS:
                continue
            out[field_key] = {sp["name"] for sp in s["spells"] if sp["name"]}
        return out

    def icon_url(self, spell_name: str, size: int = 32) -> str:
        if not spell_name:
            return ""
        icon_id = (
            self._icon_by_name.get(spell_name)
            or self._icon_by_name_lower.get(spell_name.lower())
        )
        return _spell_render_url(icon_id or spell_name, size)


# ---------------------------------------------------------------------------
# Singleton loader
# ---------------------------------------------------------------------------

_catalog_instance: AlbionSpellCatalog | None = None


def _load_seed(path: Path) -> dict[str, dict]:
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as f:
        payload = json.load(f)
    return payload.get("spells", {}) or {}


def get_spell_catalog() -> AlbionSpellCatalog:
    """Return the shared spell catalog singleton (loaded once, cached)."""
    global _catalog_instance
    if _catalog_instance is None:
        _catalog_instance = AlbionSpellCatalog(_load_seed(_DEFAULT_SEED_PATH))
    return _catalog_instance


def reload_spell_catalog(seed_path: Path | None = None) -> AlbionSpellCatalog:
    """Force a fresh load (e.g. in tests)."""
    global _catalog_instance
    path = seed_path if seed_path is not None else _DEFAULT_SEED_PATH
    _catalog_instance = AlbionSpellCatalog(_load_seed(path))
    return _catalog_instance


# ---------------------------------------------------------------------------
# Module-level convenience wrappers
# ---------------------------------------------------------------------------

def get_spells_for_item(item_id: str) -> dict | None:
    return get_spell_catalog().get_for_item(item_id)


def get_spell_icon_url(spell_name: str, size: int = 32) -> str:
    return get_spell_catalog().icon_url(spell_name, size)
